### ISSUE TITLE
List button does not work in Yambase menu

### ISSUE THREAD

**Issue by bauchetg** [solgenomics/yambase#1]
List opption doesnt not respond when clicking.
Here is the error message from Browser console:

 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.js:364:0
JQMIGRATE: Logging is active jquerymigrate.js:6:141
DEBUG: Javascript Cookie Setting: Works! Logging.js:12:284
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.js:364:0
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/

**Comment by aiminy** [comment]
Caught exception in SGN::View::JavaScript->process "Can't call method "file" on an undefined value at /home/aiminy/cxgn/local-lib/lib/perl5/Catalyst/View/JavaScript/Minifier/XS.pm line 150."

**Comment by nickmorales** [comment]
fixed here ddeb0337f7589b88e68e8a70efd2bc91b2d1c849 . need to pull changes to server

**Comment by nickmorales** [comment]
this is a better solution 01e48d40513d8c7750b1fea2acf82403c42cd6da
